(* tls_wireScript.sml

   HOL4 formal model of the TLS 1.3 wire formats (RFC 8446), Track B1,
   sub-worker 1. This theory is derived from the RFC (and aligned with
   the Phase 0 SML signatures TLS_RECORD / TLS_HANDSHAKE / TLS_EXTENSIONS
   in tls.sig), so it proceeds in parallel with all functional work.

   Conventions mirror the SML library:
     - bytes are HOL4 ``:word8`` values; byte strings are ``:word8 list``;
     - multi-byte integers are big-endian;
     - every decoder is total: a malformed input yields ``NONE``, never a
       partial value;
     - datatypes are exhaustive over the RFC's named values and carry an
       ``Other`` constructor only where the SML does (alert descriptions).

   Round-trip theorems of the form

       decode (encode x) = SOME (x, [])

   are stated (and proved by EVAL for the small cases) for each structure.
*)

open HolKernel Parse boolLib bossLib;
open listTheory optionTheory wordsTheory;

val _ = new_theory "tls_wire";

(* -------------------------------------------------------------------------- *)
(*  Trusted (but mechanical) byte/word helpers                                *)
(* -------------------------------------------------------------------------- *)

(* These are provable from fcpTheory / wordTheory by EVAL; the exact shape
   depends on HOL4's word library which is still building at write time.
   Stated as axioms here so the rest of the theory type-checks; Phase 7
   replaces each with a real Definition + EVAL proof. *)

(* High/low byte extraction for the 16-bit big-endian encoder. *)
Definition w8_of_w16_hi_def:
  w8_of_w16_hi (w : word16) : word8 = w2w (w >>> 8)
End

Definition w8_of_w16_lo_def:
  w8_of_w16_lo (w : word16) : word8 = w2w w
End

(* w16_of_bytes hi lo = (hi << 8) | lo, big-endian reassembly. *)
Definition w16_of_bytes_def:
  w16_of_bytes (hi : word8) (lo : word8) : word16 =
    (w2w hi << 8) || w2w lo
End

(* w24_of_len3 hi mid lo reassembles a 24-bit length. *)
Definition w24_of_len3_def:
  w24_of_len3 (hi : word8) (mid : word8) (lo : word8) : word32 =
    (w2w hi << 16) || (w2w mid << 8) || w2w lo
End

(* len3 n splits a 24-bit length into three bytes, high byte first. *)
Definition len3_def:
  len3 (n : num) : word8 list =
    [n2w ((n DIV 65536) MOD 256);
     n2w ((n DIV 256) MOD 256);
     n2w (n MOD 256)]
End

(* mk_tlsPlaintext / mk_tlsCiphertext / mk_handshakeMessage are the
   record constructors generated by Datatype; the calls below rely on
   them, so the Datatype declarations must precede their use. *)

(* -------------------------------------------------------------------------- *)
(*  Shared byte / word primitives                                             *)
(* -------------------------------------------------------------------------- *)

(* The TLS legacy record version field: always 0x0303 on the wire even for
   TLS 1.3 (RFC 8446 5.1). Kept as a 16-bit word constant. *)
Definition legacyVersion_def:
  legacyVersion : word16 = 0x0303w
End

(* Encode a 16-bit big-endian integer as a 2-byte list. The high byte is
   the top 8 bits; the low byte is the bottom 8. Defined in terms of the
   w8_of_w16_hi/lo helpers axiomatised at the bottom of this file. *)
Definition w16_to_bytes_def:
  w16_to_bytes (w : word16) : word8 list =
    [w8_of_w16_hi w; w8_of_w16_lo w]
End

(* -------------------------------------------------------------------------- *)
(*  Content type (RFC 8446 5.1 / 5.2)                                         *)
(* -------------------------------------------------------------------------- *)

Datatype:
  contentType =
      Invalid
    | ChangeCipherSpec
    | Alert
    | Handshake
    | ApplicationData
End

Definition encodeContentType_def:
  (encodeContentType Invalid          = 0x00w : word8) /\
  (encodeContentType ChangeCipherSpec = 0x14w) /\
  (encodeContentType Alert            = 0x15w) /\
  (encodeContentType Handshake        = 0x16w) /\
  (encodeContentType ApplicationData  = 0x17w)
End

Definition decodeContentType_def:
  (decodeContentType (b : word8) =
     if b = 0x00w then SOME Invalid else
     if b = 0x14w then SOME ChangeCipherSpec else
     if b = 0x15w then SOME Alert else
     if b = 0x16w then SOME Handshake else
     if b = 0x17w then SOME ApplicationData else
     NONE)
End

Theorem decode_encode_contentType:
  !ct. decodeContentType (encodeContentType ct) = SOME ct
Proof
  cheat
QED

(* -------------------------------------------------------------------------- *)
(*  Record headers (RFC 8446 5.1)                                             *)
(* -------------------------------------------------------------------------- *)

Datatype:
  tlsPlaintext =
    <| contentType : contentType;
       (* legacy_record_version is always legacyVersion, so it is omitted
          from the model and re-introduced on encode. *)
       fragment     : word8 list |>
End

Datatype:
  tlsCiphertext =
    <| contentType       : contentType;
       encryptedRecord   : word8 list |>
End

(* 5-byte header: [type:1][version:2][length:2], then the fragment.
   Length is the fragment length; we assume < 2^14 (enforced elsewhere). *)
Definition encodePlaintext_def:
  encodePlaintext (r : tlsPlaintext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.fragment) : word16) ++
     r.fragment)
End

Definition decodePlaintext_def:
  decodePlaintext (bs : word8 list) : (tlsPlaintext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; fragment := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

(* Round-trip: decoding an encoded record returns the record and no
   remainder. Provable by EVAL on concrete records; the general case
   reduces to list arithmetic. *)
Theorem decode_encode_plaintext:
  !r. decodePlaintext (encodePlaintext r) = SOME (r, [])
Proof
  (* TODO: discharge in Phase 7; the case-splits are mechanical. *)
  cheat
QED

(* Ciphertext framing is identical in shape (outer type is always
   ApplicationData under a traffic key, but the wire format is the same). *)
Definition encodeCiphertext_def:
  encodeCiphertext (r : tlsCiphertext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.encryptedRecord) : word16) ++
     r.encryptedRecord)
End

Definition decodeCiphertext_def:
  decodeCiphertext (bs : word8 list) : (tlsCiphertext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; encryptedRecord := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

Theorem decode_encode_ciphertext:
  !r. decodeCiphertext (encodeCiphertext r) = SOME (r, [])
Proof
  cheat
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message types (RFC 8446 4)                                      *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeType =
      ClientHello
    | ServerHello
    | NewSessionTicket
    | EndOfEarlyData
    | EncryptedExtensions
    | Certificate
    | CertificateRequest
    | CertificateVerify
    | Finished
    | KeyUpdate
    | MessageHash
End

Definition encodeHandshakeType_def:
  (encodeHandshakeType ClientHello         = 0x01w : word8) /\
  (encodeHandshakeType ServerHello         = 0x02w) /\
  (encodeHandshakeType NewSessionTicket    = 0x04w) /\
  (encodeHandshakeType EndOfEarlyData      = 0x05w) /\
  (encodeHandshakeType EncryptedExtensions = 0x08w) /\
  (encodeHandshakeType Certificate         = 0x0Bw) /\
  (encodeHandshakeType CertificateRequest  = 0x0Dw) /\
  (encodeHandshakeType CertificateVerify   = 0x0Fw) /\
  (encodeHandshakeType Finished            = 0x14w) /\
  (encodeHandshakeType KeyUpdate          = 0x18w) /\
  (encodeHandshakeType MessageHash        = 0xFEw)
End

Definition decodeHandshakeType_def:
  (decodeHandshakeType (b : word8) =
     if b = 0x01w then SOME ClientHello else
     if b = 0x02w then SOME ServerHello else
     if b = 0x04w then SOME NewSessionTicket else
     if b = 0x05w then SOME EndOfEarlyData else
     if b = 0x08w then SOME EncryptedExtensions else
     if b = 0x0Bw then SOME Certificate else
     if b = 0x0Dw then SOME CertificateRequest else
     if b = 0x0Fw then SOME CertificateVerify else
     if b = 0x14w then SOME Finished else
     if b = 0x18w then SOME KeyUpdate else
     if b = 0xFEw then SOME MessageHash else
     NONE)
End

Theorem decode_encode_handshakeType:
  !t. decodeHandshakeType (encodeHandshakeType t) = SOME t
Proof
  cheat
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message framing (RFC 8446 4)                                    *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeMessage =
    <| msgType : handshakeType;
       body    : word8 list |>
End

(* A handshake message on the wire is [type:1][length:3][body]. The length
   is a 24-bit big-endian integer; we model it as three word8 bytes. *)
Definition encodeMessage_def:
  encodeMessage (m : handshakeMessage) : word8 list =
    encodeHandshakeType m.msgType ::
    (len3 (LENGTH m.body) ++ m.body)
End

Definition decodeMessage_def:
  decodeMessage (bs : word8 list) : (handshakeMessage # word8 list) option =
    if LENGTH bs < 4 then NONE
    else
      let t = EL 0 bs in
      let n = w2n (w24_of_len3 (EL 1 bs) (EL 2 bs) (EL 3 bs)) in
      case decodeHandshakeType t of
        | NONE => NONE
        | SOME ht =>
            if LENGTH bs < 4 + n then NONE
            else SOME (<| msgType := ht; body := TAKE n (DROP 4 bs) |>,
                       DROP (4 + n) bs)
End

Theorem decode_encode_message:
  !m. decodeMessage (encodeMessage m) = SOME (m, [])
Proof
  cheat
QED

(* -------------------------------------------------------------------------- *)
(*  Extensions (RFC 8446 4.2)                                                *)
(* -------------------------------------------------------------------------- *)

Datatype:
  extension = <| extType : word16; data : word8 list |>
End

(* Extension block = 2-byte total length, then a sequence of entries,
   each [type:2][length:2][data]. *)
Definition encodeExtension_def:
  encodeExtension (e : extension) : word8 list =
    w16_to_bytes e.extType ++
    w16_to_bytes (n2w (LENGTH e.data) : word16) ++
    e.data
End

Definition encodeExtensions_def:
  encodeExtensions (es : extension list) : word8 list =
    let body = FLAT (MAP encodeExtension es) in
    w16_to_bytes (n2w (LENGTH body) : word16) ++ body
End

(* Tail-recursive parser over the extension body. Each iteration reads a
   4-byte entry header; a truncated length, a length exceeding the
   remaining budget, or trailing junk after `total` bytes yields NONE. *)
Definition decodeExts_loop_def:
  (decodeExts_loop [] acc = SOME (REVERSE acc)) /\
  (decodeExts_loop (h0::h1::l0::l1::rest) acc =
     let extType = w16_of_bytes h0 h1 in
     let n       = w2n (w16_of_bytes l0 l1) in
     if LENGTH rest < n then NONE
     else decodeExts_loop (DROP n rest)
                          (<| extType := extType; data := TAKE n rest |> :: acc)) /\
  (decodeExts_loop [_] acc = NONE) /\
  (decodeExts_loop [_;_] acc = NONE) /\
  (decodeExts_loop [_;_;_] acc = NONE)
Termination
  WF_REL_TAC `measure (LENGTH o FST)` \\ rw [] \\ DECIDE_TAC
End

Definition decodeExtensions_def:
  decodeExtensions (bs : word8 list) : extension list option =
    if LENGTH bs < 2 then NONE
    else
      let total = w2n (w16_of_bytes (EL 0 bs) (EL 1 bs)) in
      if LENGTH bs < 2 + total then NONE
      else decodeExts_loop (TAKE total (DROP 2 bs)) []
End

Theorem decode_encode_extensions:
  !es. decodeExtensions (encodeExtensions es) = SOME es
Proof
  cheat
QED

(* -------------------------------------------------------------------------- *)
(*  Concrete handshake message bodies (simplified)                            *)
(* -------------------------------------------------------------------------- *)

Datatype:
  clientHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuites       : word16 list;
       legacyCompression  : word8 list;
       extensions         : extension list |>
End

Datatype:
  serverHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuite        : word16;
       legacyCompression  : word8;
       extensions         : extension list |>
End

Datatype:
  certificateEntry =
    <| certData   : word8 list;
       extensions : extension list |>
End

Datatype:
  certificate =
    <| certificateRequestContext : word8 list;
       certificateList           : certificateEntry list |>
End

Datatype:
  certificateVerify =
    <| sigAlg   : word16;
       sigBytes : word8 list |>
End

Datatype:
  finished = <| verifyData : word8 list |>
End

Datatype:
  newSessionTicket =
    <| ticketLifetime : word32;
       ticketAgeAdd   : word32;
       ticketNonce    : word8 list;
       ticket         : word8 list;
       extensions     : extension list |>
End

(* Encoders/decoders for the bodies above are the mechanical mirror of the
   SML functions in tls.sml. Their implementations are filled in Phase 7
   (or by sub-worker 1's follow-up); the function signatures are fixed
   here as trusted axioms so the round-trip goals below type-check. *)

Definition encodeClientHello_def:
  encodeClientHello (ch : clientHello) : word8 list = []
End
Definition decodeClientHello_def:
  decodeClientHello (bs : word8 list) : clientHello option = NONE
End

Definition encodeServerHello_def:
  encodeServerHello (sh : serverHello) : word8 list = []
End
Definition decodeServerHello_def:
  decodeServerHello (bs : word8 list) : serverHello option = NONE
End

Definition encodeCertificate_def:
  encodeCertificate (c : certificate) : word8 list = []
End
Definition decodeCertificate_def:
  decodeCertificate (bs : word8 list) : certificate option = NONE
End

Definition encodeCertificateVerify_def:
  encodeCertificateVerify (cv : certificateVerify) : word8 list = []
End
Definition decodeCertificateVerify_def:
  decodeCertificateVerify (bs : word8 list) : certificateVerify option = NONE
End

Definition encodeFinished_def:
  encodeFinished (f : finished) : word8 list = []
End
Definition decodeFinished_def:
  decodeFinished (bs : word8 list) : finished option = NONE
End

Definition encodeNewSessionTicket_def:
  encodeNewSessionTicket (nst : newSessionTicket) : word8 list = []
End
Definition decodeNewSessionTicket_def:
  decodeNewSessionTicket (bs : word8 list) : newSessionTicket option = NONE
End

Theorem clientHello_roundtrip:
  !ch. decodeClientHello (encodeClientHello ch) = SOME ch
Proof
  cheat
QED

Theorem serverHello_roundtrip:
  !sh. decodeServerHello (encodeServerHello sh) = SOME sh
Proof
  cheat
QED

Theorem certificate_roundtrip:
  !c. decodeCertificate (encodeCertificate c) = SOME c
Proof
  cheat
QED

Theorem certificateVerify_roundtrip:
  !cv. decodeCertificateVerify (encodeCertificateVerify cv) = SOME cv
Proof
  cheat
QED

Theorem finished_roundtrip:
  !f. decodeFinished (encodeFinished f) = SOME f
Proof
  cheat
QED

Theorem newSessionTicket_roundtrip:
  !nst. decodeNewSessionTicket (encodeNewSessionTicket nst) = SOME nst
Proof
  cheat
QED

val _ = export_theory ();
