(* tls_wireScript.sml

   HOL4 formal model of the TLS 1.3 wire formats (RFC 8446), Track B1,
   sub-worker 1. This theory is derived from the RFC (and aligned with
   the Phase 0 SML signatures TLS_RECORD / TLS_HANDSHAKE / TLS_EXTENSIONS
   in tls.sig), so it proceeds in parallel with all functional work.

   Conventions mirror the SML library:
     - bytes are HOL4 ``:word8`` values; byte strings are ``:word8 list``;
     - multi-byte integers are big-endian;
     - every decoder is total: a malformed input yields ``NONE``, never a
       partial value;
     - datatypes are exhaustive over the RFC's named values and carry an
       ``Other`` constructor only where the SML does (alert descriptions).

   Round-trip theorems of the form

       decode (encode x) = SOME (x, [])

   are stated (and proved by EVAL for the small cases) for each structure.
*)

open HolKernel Parse boolLib bossLib;
open listTheory optionTheory wordsTheory;

val _ = new_theory "tls_wire";

(* -------------------------------------------------------------------------- *)
(*  Trusted (but mechanical) byte/word helpers                                *)
(* -------------------------------------------------------------------------- *)

(* These are provable from fcpTheory / wordTheory by EVAL; the exact shape
   depends on HOL4's word library which is still building at write time.
   Stated as axioms here so the rest of the theory type-checks; Phase 7
   replaces each with a real Definition + EVAL proof. *)

(* High/low byte extraction for the 16-bit big-endian encoder. *)
Definition w8_of_w16_hi_def:
  w8_of_w16_hi (w : word16) : word8 = w2w (w >>> 8)
End

Definition w8_of_w16_lo_def:
  w8_of_w16_lo (w : word16) : word8 = w2w w
End

(* w16_of_bytes hi lo = (hi << 8) | lo, big-endian reassembly. *)
Definition w16_of_bytes_def:
  w16_of_bytes (hi : word8) (lo : word8) : word16 =
    (w2w hi << 8) || w2w lo
End

(* w24_of_len3 hi mid lo reassembles a 24-bit length. *)
Definition w24_of_len3_def:
  w24_of_len3 (hi : word8) (mid : word8) (lo : word8) : word32 =
    (w2w hi << 16) || (w2w mid << 8) || w2w lo
End

(* len3 n splits a 24-bit length into three bytes, high byte first. *)
Definition len3_def:
  len3 (n : num) : word8 list =
    [n2w ((n DIV 65536) MOD 256);
     n2w ((n DIV 256) MOD 256);
     n2w (n MOD 256)]
End

(* mk_tlsPlaintext / mk_tlsCiphertext / mk_handshakeMessage are the
   record constructors generated by Datatype; the calls below rely on
   them, so the Datatype declarations must precede their use. *)

(* -------------------------------------------------------------------------- *)
(*  Shared byte / word primitives                                             *)
(* -------------------------------------------------------------------------- *)

(* The TLS legacy record version field: always 0x0303 on the wire even for
   TLS 1.3 (RFC 8446 5.1). Kept as a 16-bit word constant. *)
Definition legacyVersion_def:
  legacyVersion : word16 = 0x0303w
End

(* Encode a 16-bit big-endian integer as a 2-byte list. The high byte is
   the top 8 bits; the low byte is the bottom 8. Defined in terms of the
   w8_of_w16_hi/lo helpers axiomatised at the bottom of this file. *)
Definition w16_to_bytes_def:
  w16_to_bytes (w : word16) : word8 list =
    [w8_of_w16_hi w; w8_of_w16_lo w]
End

(* -------------------------------------------------------------------------- *)
(*  Word reconstruction lemmas (proved by bit-blasting / w2n arithmetic)      *)
(* -------------------------------------------------------------------------- *)

(* A 16-bit word survives the split-into-bytes / reassemble round-trip. *)
Theorem w16_of_to_bytes:
  !w:word16. w16_of_bytes (w8_of_w16_hi w) (w8_of_w16_lo w) = w
Proof
  rw[w16_of_bytes_def, w8_of_w16_hi_def, w8_of_w16_lo_def] >>
  blastLib.BBLAST_TAC
QED

(* Encoding a length < 2^16 as two bytes and reading it back yields the
   length unchanged. *)
Theorem w16_len_roundtrip:
  !len. len < 65536 ==>
        w2n (w16_of_bytes (w8_of_w16_hi (n2w len)) (w8_of_w16_lo (n2w len))) = len
Proof
  rw[w16_of_to_bytes] >>
  simp[w2n_n2w] >>
  `dimword (:16) = 65536` by EVAL_TAC >>
  simp[]
QED

(* A 24-bit value held in a word32 survives split/reassemble.  The bound
   gives the bit-blaster the information that the top byte is zero. *)
Theorem w24_recon:
  !w:word32. w <+ 0x1000000w ==>
     w24_of_len3 (w2w (w >>> 16)) (w2w (w >>> 8)) (w2w w) = w
Proof
  rw[w24_of_len3_def] >> rpt strip_tac >> blastLib.FULL_BBLAST_TAC
QED

(* n2w absorbs a redundant MOD 256 at type word8 (dimword(:8) = 256). *)
Theorem n2w_mod256:
  !a. (n2w (a MOD 256) : word8) = n2w a
Proof
  strip_tac >> `256 = dimword (:8)` by EVAL_TAC >> pop_assum SUBST1_TAC >>
  simp[n2w_mod]
QED

(* Encoding a length < 2^24 as three big-endian bytes and reading it back
   yields the length unchanged. *)
Theorem len3_w24_roundtrip:
  !len. len < 16777216 ==>
    w2n (w24_of_len3 (n2w ((len DIV 65536) MOD 256))
                     (n2w ((len DIV 256) MOD 256))
                     (n2w (len MOD 256))) = len
Proof
  rpt strip_tac >>
  `dimword (:32) = 4294967296` by EVAL_TAC >>
  `(2:num) ** 16 = 65536` by EVAL_TAC >>
  `(2:num) ** 8 = 256` by EVAL_TAC >>
  `len MOD dimword (:32) = len` by simp[arithmeticTheory.LESS_MOD] >>
  `dimword (:8) = 256` by EVAL_TAC >>
  `w24_of_len3 (n2w ((len DIV 65536) MOD 256))
               (n2w ((len DIV 256) MOD 256))
               (n2w (len MOD 256)) = (n2w len : word32)` by (
     `(n2w ((len DIV 65536) MOD 256) : word8) = w2w ((n2w len : word32) >>> 16)` by
        simp[w2w_def, w2n_lsr, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     `(n2w ((len DIV 256) MOD 256) : word8) = w2w ((n2w len : word32) >>> 8)` by
        simp[w2w_def, w2n_lsr, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     `(n2w (len MOD 256) : word8) = w2w (n2w len : word32)` by
        simp[w2w_def, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     ASM_REWRITE_TAC[] >> irule w24_recon >>
     simp[WORD_LO, w2n_n2w]) >>
  simp[w2n_n2w]
QED

(* -------------------------------------------------------------------------- *)
(*  Content type (RFC 8446 5.1 / 5.2)                                         *)
(* -------------------------------------------------------------------------- *)

Datatype:
  contentType =
      Invalid
    | ChangeCipherSpec
    | Alert
    | Handshake
    | ApplicationData
End

Definition encodeContentType_def:
  (encodeContentType Invalid          = 0x00w : word8) /\
  (encodeContentType ChangeCipherSpec = 0x14w) /\
  (encodeContentType Alert            = 0x15w) /\
  (encodeContentType Handshake        = 0x16w) /\
  (encodeContentType ApplicationData  = 0x17w)
End

Definition decodeContentType_def:
  (decodeContentType (b : word8) =
     if b = 0x00w then SOME Invalid else
     if b = 0x14w then SOME ChangeCipherSpec else
     if b = 0x15w then SOME Alert else
     if b = 0x16w then SOME Handshake else
     if b = 0x17w then SOME ApplicationData else
     NONE)
End

Theorem decode_encode_contentType:
  !ct. decodeContentType (encodeContentType ct) = SOME ct
Proof
  Cases >> EVAL_TAC
QED

(* -------------------------------------------------------------------------- *)
(*  Record headers (RFC 8446 5.1)                                             *)
(* -------------------------------------------------------------------------- *)

Datatype:
  tlsPlaintext =
    <| contentType : contentType;
       (* legacy_record_version is always legacyVersion, so it is omitted
          from the model and re-introduced on encode. *)
       fragment     : word8 list |>
End

Datatype:
  tlsCiphertext =
    <| contentType       : contentType;
       encryptedRecord   : word8 list |>
End

(* 5-byte header: [type:1][version:2][length:2], then the fragment.
   Length is the fragment length; we assume < 2^14 (enforced elsewhere). *)
Definition encodePlaintext_def:
  encodePlaintext (r : tlsPlaintext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.fragment) : word16) ++
     r.fragment)
End

Definition decodePlaintext_def:
  decodePlaintext (bs : word8 list) : (tlsPlaintext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; fragment := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

(* Round-trip: decoding an encoded record returns the record and no
   remainder. Provable by EVAL on concrete records; the general case
   reduces to list arithmetic. *)
(* The 16-bit length field caps a fragment at 2^16-1 bytes (TLS itself caps
   records well below this, at 2^14); under that bound the round-trip holds. *)
Theorem decode_encode_plaintext:
  !r. LENGTH r.fragment < 65536 ==>
      decodePlaintext (encodePlaintext r) = SOME (r, [])
Proof
  strip_tac >> strip_tac >>
  `encodePlaintext r =
     encodeContentType r.contentType ::
     w8_of_w16_hi legacyVersion :: w8_of_w16_lo legacyVersion ::
     w8_of_w16_hi (n2w (LENGTH r.fragment)) ::
     w8_of_w16_lo (n2w (LENGTH r.fragment)) :: r.fragment`
    by simp[encodePlaintext_def, w16_to_bytes_def] >>
  simp[decodePlaintext_def, decode_encode_contentType, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "tlsPlaintext_component_equality"]
QED

(* Ciphertext framing is identical in shape (outer type is always
   ApplicationData under a traffic key, but the wire format is the same). *)
Definition encodeCiphertext_def:
  encodeCiphertext (r : tlsCiphertext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.encryptedRecord) : word16) ++
     r.encryptedRecord)
End

Definition decodeCiphertext_def:
  decodeCiphertext (bs : word8 list) : (tlsCiphertext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; encryptedRecord := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

Theorem decode_encode_ciphertext:
  !r. LENGTH r.encryptedRecord < 65536 ==>
      decodeCiphertext (encodeCiphertext r) = SOME (r, [])
Proof
  strip_tac >> strip_tac >>
  `encodeCiphertext r =
     encodeContentType r.contentType ::
     w8_of_w16_hi legacyVersion :: w8_of_w16_lo legacyVersion ::
     w8_of_w16_hi (n2w (LENGTH r.encryptedRecord)) ::
     w8_of_w16_lo (n2w (LENGTH r.encryptedRecord)) :: r.encryptedRecord`
    by simp[encodeCiphertext_def, w16_to_bytes_def] >>
  simp[decodeCiphertext_def, decode_encode_contentType, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "tlsCiphertext_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message types (RFC 8446 4)                                      *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeType =
      ClientHello
    | ServerHello
    | NewSessionTicket
    | EndOfEarlyData
    | EncryptedExtensions
    | Certificate
    | CertificateRequest
    | CertificateVerify
    | Finished
    | KeyUpdate
    | MessageHash
End

Definition encodeHandshakeType_def:
  (encodeHandshakeType ClientHello         = 0x01w : word8) /\
  (encodeHandshakeType ServerHello         = 0x02w) /\
  (encodeHandshakeType NewSessionTicket    = 0x04w) /\
  (encodeHandshakeType EndOfEarlyData      = 0x05w) /\
  (encodeHandshakeType EncryptedExtensions = 0x08w) /\
  (encodeHandshakeType Certificate         = 0x0Bw) /\
  (encodeHandshakeType CertificateRequest  = 0x0Dw) /\
  (encodeHandshakeType CertificateVerify   = 0x0Fw) /\
  (encodeHandshakeType Finished            = 0x14w) /\
  (encodeHandshakeType KeyUpdate          = 0x18w) /\
  (encodeHandshakeType MessageHash        = 0xFEw)
End

Definition decodeHandshakeType_def:
  (decodeHandshakeType (b : word8) =
     if b = 0x01w then SOME ClientHello else
     if b = 0x02w then SOME ServerHello else
     if b = 0x04w then SOME NewSessionTicket else
     if b = 0x05w then SOME EndOfEarlyData else
     if b = 0x08w then SOME EncryptedExtensions else
     if b = 0x0Bw then SOME Certificate else
     if b = 0x0Dw then SOME CertificateRequest else
     if b = 0x0Fw then SOME CertificateVerify else
     if b = 0x14w then SOME Finished else
     if b = 0x18w then SOME KeyUpdate else
     if b = 0xFEw then SOME MessageHash else
     NONE)
End

Theorem decode_encode_handshakeType:
  !t. decodeHandshakeType (encodeHandshakeType t) = SOME t
Proof
  Cases >> EVAL_TAC
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message framing (RFC 8446 4)                                    *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeMessage =
    <| msgType : handshakeType;
       body    : word8 list |>
End

(* A handshake message on the wire is [type:1][length:3][body]. The length
   is a 24-bit big-endian integer; we model it as three word8 bytes. *)
Definition encodeMessage_def:
  encodeMessage (m : handshakeMessage) : word8 list =
    encodeHandshakeType m.msgType ::
    (len3 (LENGTH m.body) ++ m.body)
End

Definition decodeMessage_def:
  decodeMessage (bs : word8 list) : (handshakeMessage # word8 list) option =
    if LENGTH bs < 4 then NONE
    else
      let t = EL 0 bs in
      let n = w2n (w24_of_len3 (EL 1 bs) (EL 2 bs) (EL 3 bs)) in
      case decodeHandshakeType t of
        | NONE => NONE
        | SOME ht =>
            if LENGTH bs < 4 + n then NONE
            else SOME (<| msgType := ht; body := TAKE n (DROP 4 bs) |>,
                       DROP (4 + n) bs)
End

(* The 24-bit length field caps a handshake body at 2^24-1 bytes (the RFC
   8446 limit); under that bound the round-trip holds. *)
Theorem decode_encode_message:
  !m. LENGTH m.body < 16777216 ==>
      decodeMessage (encodeMessage m) = SOME (m, [])
Proof
  strip_tac >> strip_tac >>
  `encodeMessage m =
     encodeHandshakeType m.msgType ::
     n2w ((LENGTH m.body DIV 65536) MOD 256) ::
     n2w ((LENGTH m.body DIV 256) MOD 256) ::
     n2w (LENGTH m.body MOD 256) :: m.body`
    by simp[encodeMessage_def, len3_def] >>
  simp[decodeMessage_def, decode_encode_handshakeType, len3_w24_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "handshakeMessage_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  Extensions (RFC 8446 4.2)                                                *)
(* -------------------------------------------------------------------------- *)

Datatype:
  extension = <| extType : word16; data : word8 list |>
End

(* Extension block = 2-byte total length, then a sequence of entries,
   each [type:2][length:2][data]. *)
Definition encodeExtension_def:
  encodeExtension (e : extension) : word8 list =
    w16_to_bytes e.extType ++
    w16_to_bytes (n2w (LENGTH e.data) : word16) ++
    e.data
End

Definition encodeExtensions_def:
  encodeExtensions (es : extension list) : word8 list =
    let body = FLAT (MAP encodeExtension es) in
    w16_to_bytes (n2w (LENGTH body) : word16) ++ body
End

(* Tail-recursive parser over the extension body. Each iteration reads a
   4-byte entry header; a truncated length, a length exceeding the
   remaining budget, or trailing junk after `total` bytes yields NONE. *)
Definition decodeExts_loop_def:
  (decodeExts_loop [] acc = SOME (REVERSE acc)) /\
  (decodeExts_loop (h0::h1::l0::l1::rest) acc =
     let extType = w16_of_bytes h0 h1 in
     let n       = w2n (w16_of_bytes l0 l1) in
     if LENGTH rest < n then NONE
     else decodeExts_loop (DROP n rest)
                          (<| extType := extType; data := TAKE n rest |> :: acc)) /\
  (decodeExts_loop [_] acc = NONE) /\
  (decodeExts_loop [_;_] acc = NONE) /\
  (decodeExts_loop [_;_;_] acc = NONE)
Termination
  WF_REL_TAC `measure (LENGTH o FST)` \\ rw [] \\ DECIDE_TAC
End

Definition decodeExtensions_def:
  decodeExtensions (bs : word8 list) : extension list option =
    if LENGTH bs < 2 then NONE
    else
      let total = w2n (w16_of_bytes (EL 0 bs) (EL 1 bs)) in
      if LENGTH bs < 2 + total then NONE
      else decodeExts_loop (TAKE total (DROP 2 bs)) []
End

(* The loop is correct: parsing the concatenation of encoded extensions
   recovers them in order (modulo the reverse-accumulator), provided each
   extension's data fits in the 2-byte length field. *)
Theorem decodeExts_loop_correct:
  !es acc.
    EVERY (\e. LENGTH e.data < 65536) es ==>
    decodeExts_loop (FLAT (MAP encodeExtension es)) acc = SOME (REVERSE acc ++ es)
Proof
  Induct
  >- simp[decodeExts_loop_def]
  >> rpt strip_tac
  >> fs[]
  >> simp[encodeExtension_def, w16_to_bytes_def]
  >> simp[decodeExts_loop_def, w16_of_to_bytes, w16_len_roundtrip,
          rich_listTheory.TAKE_LENGTH_APPEND, rich_listTheory.DROP_LENGTH_APPEND]
  >> simp[fetch "-" "extension_component_equality"]
QED

(* Full extension-block round-trip.  Two honest bounds: each extension's
   data is < 2^16 bytes, and the concatenated block is < 2^16 bytes (both
   enforced by the 2-byte length fields on the wire). *)
Theorem decode_encode_extensions:
  !es. EVERY (\e. LENGTH e.data < 65536) es /\
       LENGTH (FLAT (MAP encodeExtension es)) < 65536 ==>
       decodeExtensions (encodeExtensions es) = SOME es
Proof
  rpt strip_tac >>
  simp[decodeExtensions_def, encodeExtensions_def, w16_to_bytes_def] >>
  simp[w16_of_to_bytes, w16_len_roundtrip, rich_listTheory.TAKE_LENGTH_APPEND,
       rich_listTheory.DROP_LENGTH_APPEND] >>
  simp[decodeExts_loop_correct]
QED

(* -------------------------------------------------------------------------- *)
(*  Concrete handshake message bodies (simplified)                            *)
(* -------------------------------------------------------------------------- *)

Datatype:
  clientHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuites       : word16 list;
       legacyCompression  : word8 list;
       extensions         : extension list |>
End

Datatype:
  serverHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuite        : word16;
       legacyCompression  : word8;
       extensions         : extension list |>
End

Datatype:
  certificateEntry =
    <| certData   : word8 list;
       extensions : extension list |>
End

Datatype:
  certificate =
    <| certificateRequestContext : word8 list;
       certificateList           : certificateEntry list |>
End

Datatype:
  certificateVerify =
    <| sigAlg   : word16;
       sigBytes : word8 list |>
End

Datatype:
  finished = <| verifyData : word8 list |>
End

Datatype:
  newSessionTicket =
    <| ticketLifetime : word32;
       ticketAgeAdd   : word32;
       ticketNonce    : word8 list;
       ticket         : word8 list;
       extensions     : extension list |>
End

(* --- Finished (RFC 8446 4.4.4) -----------------------------------------

   The Finished body is exactly verify_data (no internal framing); its
   length is fixed by the hash and is always non-empty.  This mirrors the
   SML `encodeFinished`/`decodeFinished` in tls.sml, which return NONE on an
   empty input. *)

Definition encodeFinished_def:
  encodeFinished (f : finished) : word8 list = f.verifyData
End
Definition decodeFinished_def:
  decodeFinished (bs : word8 list) : finished option =
    if bs = [] then NONE else SOME <| verifyData := bs |>
End

Theorem finished_roundtrip:
  !f. f.verifyData <> [] ==> decodeFinished (encodeFinished f) = SOME f
Proof
  rw[encodeFinished_def, decodeFinished_def] >>
  simp[fetch "-" "finished_component_equality"]
QED

(* --- CertificateVerify (RFC 8446 4.4.3) --------------------------------

   Wire form: [sigAlg:2][sigLen:2][signature].  Mirrors the SML
   `encodeCertificateVerify`/`decodeCertificateVerify`. *)

Definition encodeCertificateVerify_def:
  encodeCertificateVerify (cv : certificateVerify) : word8 list =
    w16_to_bytes cv.sigAlg ++
    w16_to_bytes (n2w (LENGTH cv.sigBytes) : word16) ++
    cv.sigBytes
End
Definition decodeCertificateVerify_def:
  decodeCertificateVerify (bs : word8 list) : certificateVerify option =
    if LENGTH bs < 4 then NONE
    else
      let sigAlg = w16_of_bytes (EL 0 bs) (EL 1 bs) in
      let n      = w2n (w16_of_bytes (EL 2 bs) (EL 3 bs)) in
      if LENGTH bs < 4 + n then NONE
      else SOME <| sigAlg := sigAlg; sigBytes := TAKE n (DROP 4 bs) |>
End

Theorem certificateVerify_roundtrip:
  !cv. LENGTH cv.sigBytes < 65536 ==>
       decodeCertificateVerify (encodeCertificateVerify cv) = SOME cv
Proof
  strip_tac >> strip_tac >>
  `encodeCertificateVerify cv =
     w8_of_w16_hi cv.sigAlg :: w8_of_w16_lo cv.sigAlg ::
     w8_of_w16_hi (n2w (LENGTH cv.sigBytes)) ::
     w8_of_w16_lo (n2w (LENGTH cv.sigBytes)) :: cv.sigBytes`
    by simp[encodeCertificateVerify_def, w16_to_bytes_def] >>
  simp[decodeCertificateVerify_def, w16_of_to_bytes, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, fetch "-" "certificateVerify_component_equality"]
QED

(* --------------------------------------------------------------------------
    Reusable framing helpers for the composite handshake bodies

    ClientHello / ServerHello / Certificate / NewSessionTicket carry nested,
    length-prefixed vectors plus a trailing extension block.  We build the
    codecs out of small, individually-proved pieces:

      * `encodeOpaque8`  : a 1-byte length-prefixed opaque byte string
                           (legacy_session_id, certificate_request_context,
                           ticket_nonce, ClientHello.legacy_compression).
      * `encodeW16List`  : a 2-byte length-prefixed list of `word16` (the
                           cipher-suite list of a ClientHello).
      * `decodeCertEntries_loop` : the inner list-of-CertificateEntry parser,
                           with a loop-correctness lemma analogous to
                           `decodeExts_loop_correct`.

    Every round-trip below carries the honest length side conditions the wire
    length fields impose (the same `(bound)` style as the framing layer above).
   -------------------------------------------------------------------------- *)

(* w32_to_bytes / w32_of_bytes : big-endian 4-byte integers (ticket lifetime
   and age-add).  Mirrors `word32ToBytes`/`bytesToWord32` in tls.sml. *)
Definition w32_to_bytes_def:
  w32_to_bytes (w : word32) : word8 list =
    [w2w (w >>> 24); w2w (w >>> 16); w2w (w >>> 8); w2w w]
End

Definition w32_of_bytes_def:
  w32_of_bytes (a:word8) (b:word8) (c:word8) (d:word8) : word32 =
    (w2w a << 24) || (w2w b << 16) || (w2w c << 8) || w2w d
End

Theorem w32_of_to_bytes:
  !w:word32. w32_of_bytes (w2w (w >>> 24)) (w2w (w >>> 16))
                          (w2w (w >>> 8)) (w2w w) = w
Proof
  rw[w32_of_bytes_def] >> blastLib.BBLAST_TAC
QED

(* --- 1-byte length-prefixed opaque string --------------------------------- *)

Definition encodeOpaque8_def:
  encodeOpaque8 (bs : word8 list) : word8 list =
    n2w (LENGTH bs) :: bs
End

(* --- 2-byte length-prefixed word16 list (cipher suites) ------------------- *)

Definition encodeW16ListBody_def:
  encodeW16ListBody (ws : word16 list) : word8 list =
    FLAT (MAP w16_to_bytes ws)
End

Definition encodeW16List_def:
  encodeW16List (ws : word16 list) : word8 list =
    w16_to_bytes (n2w (LENGTH (encodeW16ListBody ws)) : word16) ++
    encodeW16ListBody ws
End

(* Parse exactly `k` word16s from the front of a byte list (k is the count,
   derived from the 2-byte length / 2).  Returns the list and the remainder. *)
Definition decodeW16s_loop_def:
  (decodeW16s_loop 0 bs = SOME ([], bs)) /\
  (decodeW16s_loop (SUC k) [] = NONE) /\
  (decodeW16s_loop (SUC k) [_] = NONE) /\
  (decodeW16s_loop (SUC k) (h0::h1::rest) =
     case decodeW16s_loop k rest of
       | NONE => NONE
       | SOME (ws, rem) => SOME (w16_of_bytes h0 h1 :: ws, rem))
End

Theorem decodeW16s_loop_correct:
  !ws rest.
    decodeW16s_loop (LENGTH ws) (FLAT (MAP w16_to_bytes ws) ++ rest) =
      SOME (ws, rest)
Proof
  Induct
  >- simp[decodeW16s_loop_def]
  >> rpt strip_tac
  >> simp[w16_to_bytes_def, decodeW16s_loop_def, w16_of_to_bytes]
QED

(* Each encoded word16 occupies exactly two bytes, so the body length is
   twice the suite count. *)
Theorem encodeW16ListBody_length:
  !ws. LENGTH (encodeW16ListBody ws) = 2 * LENGTH ws
Proof
  simp[encodeW16ListBody_def] >>
  Induct >> simp[w16_to_bytes_def, arithmeticTheory.MULT_CLAUSES]
QED

(* --- NewSessionTicket (RFC 8446 4.6.1) -----------------------------------

   Wire form (mirrors `encodeNewSessionTicket` in tls.sml):
     [lifetime:4][ageAdd:4][nonceLen:1][nonce][ticketLen:3][ticket][exts].
   The trailing extension block is always present (>= 2 bytes) so the SML
   decoder's "no trailing bytes => extensions = []" branch is never taken on
   our encoded output. *)

Definition encodeNewSessionTicket_def:
  encodeNewSessionTicket (t : newSessionTicket) : word8 list =
    w32_to_bytes t.ticketLifetime ++
    w32_to_bytes t.ticketAgeAdd ++
    encodeOpaque8 t.ticketNonce ++
    len3 (LENGTH t.ticket) ++ t.ticket ++
    encodeExtensions t.extensions
End

Definition decodeNewSessionTicket_def:
  decodeNewSessionTicket (bs : word8 list) : newSessionTicket option =
    if LENGTH bs < 9 then NONE
    else
      let lifetime = w32_of_bytes (EL 0 bs) (EL 1 bs) (EL 2 bs) (EL 3 bs) in
      let ageAdd   = w32_of_bytes (EL 4 bs) (EL 5 bs) (EL 6 bs) (EL 7 bs) in
      let nonceLen = w2n (EL 8 bs) in
      let r1       = DROP 9 bs in
      if LENGTH r1 < nonceLen then NONE
      else
        let nonce = TAKE nonceLen r1 in
        let r2    = DROP nonceLen r1 in
        if LENGTH r2 < 3 then NONE
        else
          let tlen = w2n (w24_of_len3 (EL 0 r2) (EL 1 r2) (EL 2 r2)) in
          let r3   = DROP 3 r2 in
          if LENGTH r3 < tlen then NONE
          else
            let ticket = TAKE tlen r3 in
            let r4     = DROP tlen r3 in
            case decodeExtensions r4 of
              | NONE => NONE
              | SOME exts =>
                  SOME <| ticketLifetime := lifetime;
                          ticketAgeAdd   := ageAdd;
                          ticketNonce    := nonce;
                          ticket         := ticket;
                          extensions     := exts |>
End

Definition wfNewSessionTicket_def:
  wfNewSessionTicket (t : newSessionTicket) <=>
    LENGTH t.ticketNonce < 256 /\
    LENGTH t.ticket < 16777216 /\
    EVERY (\e. LENGTH e.data < 65536) t.extensions /\
    LENGTH (FLAT (MAP encodeExtension t.extensions)) < 65536
End

Theorem decode_encode_newSessionTicket:
  !t. wfNewSessionTicket t ==>
      decodeNewSessionTicket (encodeNewSessionTicket t) = SOME t
Proof
  rw[wfNewSessionTicket_def] >>
  `encodeNewSessionTicket t =
     w2w (t.ticketLifetime >>> 24) :: w2w (t.ticketLifetime >>> 16) ::
     w2w (t.ticketLifetime >>> 8) :: w2w t.ticketLifetime ::
     w2w (t.ticketAgeAdd >>> 24) :: w2w (t.ticketAgeAdd >>> 16) ::
     w2w (t.ticketAgeAdd >>> 8) :: w2w t.ticketAgeAdd ::
     n2w (LENGTH t.ticketNonce) ::
     (t.ticketNonce ++
      (n2w ((LENGTH t.ticket DIV 65536) MOD 256) ::
       n2w ((LENGTH t.ticket DIV 256) MOD 256) ::
       n2w (LENGTH t.ticket MOD 256) ::
       (t.ticket ++ encodeExtensions t.extensions)))`
    by simp[encodeNewSessionTicket_def, w32_to_bytes_def, encodeOpaque8_def,
            len3_def] >>
  simp[decodeNewSessionTicket_def] >>
  simp[w32_of_to_bytes] >>
  `(n2w (LENGTH t.ticketNonce) : word8) = n2w (LENGTH t.ticketNonce)` by simp[] >>
  simp[w2n_n2w] >>
  `LENGTH t.ticketNonce MOD dimword (:8) = LENGTH t.ticketNonce`
    by (`dimword (:8) = 256` by EVAL_TAC >> simp[]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[len3_w24_roundtrip] >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[decode_encode_extensions] >>
  simp[fetch "-" "newSessionTicket_component_equality"]
QED

(* --- Certificate (RFC 8446 4.4.2) ----------------------------------------

   Wire form (mirrors `encodeCertificate` in tls.sml):
     [ctxLen:1][ctx][entriesTotalLen:3][entries]
   where each entry is
     [certDataLen:3][certData][extensions block].

   The inner entry parser needs to know how far each entry extends; the
   extension block is self-describing (its 2-byte length header), so we use a
   *remainder-passing* extension decoder `decodeExtensionsR`, then a
   `decodeCertEntries_loop` analogous to `decodeExts_loop`. *)

(* Remainder-passing extension-block decoder: like `decodeExtensions` but
   returns the bytes following the 2 + total-byte block. *)
Definition decodeExtensionsR_def:
  decodeExtensionsR (bs : word8 list) : (extension list # word8 list) option =
    if LENGTH bs < 2 then NONE
    else
      let total = w2n (w16_of_bytes (EL 0 bs) (EL 1 bs)) in
      if LENGTH bs < 2 + total then NONE
      else
        case decodeExts_loop (TAKE total (DROP 2 bs)) [] of
          | NONE => NONE
          | SOME es => SOME (es, DROP (2 + total) bs)
End

Theorem decodeExtensionsR_correct:
  !es rest.
    EVERY (\e. LENGTH e.data < 65536) es /\
    LENGTH (FLAT (MAP encodeExtension es)) < 65536 ==>
    decodeExtensionsR (encodeExtensions es ++ rest) = SOME (es, rest)
Proof
  rpt strip_tac >>
  simp[decodeExtensionsR_def, encodeExtensions_def, w16_to_bytes_def] >>
  simp[w16_of_to_bytes, w16_len_roundtrip, rich_listTheory.TAKE_LENGTH_APPEND,
       rich_listTheory.DROP_LENGTH_APPEND] >>
  simp[GSYM rich_listTheory.APPEND_ASSOC] >>
  simp[w16_of_to_bytes, w16_len_roundtrip, rich_listTheory.TAKE_LENGTH_APPEND,
       rich_listTheory.DROP_LENGTH_APPEND] >>
  simp[decodeExts_loop_correct]
QED

Definition encodeCertEntry_def:
  encodeCertEntry (e : certificateEntry) : word8 list =
    len3 (LENGTH e.certData) ++ e.certData ++ encodeExtensions e.extensions
End

Definition encodeCertEntries_def:
  encodeCertEntries (es : certificateEntry list) : word8 list =
    FLAT (MAP encodeCertEntry es)
End

(* Loop over the (already length-delimited) entries block.  Each iteration
   reads a 3-byte certData length, the cert data, then a self-describing
   extension block.  An empty input ends the list. *)
Definition decodeCertEntries_loop_def:
  decodeCertEntries_loop (bs : word8 list) acc =
    if bs = [] then SOME (REVERSE acc)
    else if LENGTH bs < 3 then NONE
    else
      let n  = w2n (w24_of_len3 (EL 0 bs) (EL 1 bs) (EL 2 bs)) in
      let r1 = DROP 3 bs in
      if LENGTH r1 < n then NONE
      else
        let cd = TAKE n r1 in
        let r2 = DROP n r1 in
        case decodeExtensionsR r2 of
          | NONE => NONE
          | SOME (es, r3) =>
              decodeCertEntries_loop r3
                (<| certData := cd; extensions := es |> :: acc)
Termination
  WF_REL_TAC `measure (LENGTH o FST)` >> rw[] >>
  imp_res_tac (Q.prove(
    `!bs es r. decodeExtensionsR bs = SOME (es, r) ==> LENGTH r <= LENGTH bs`,
    rw[decodeExtensionsR_def] >> gvs[AllCaseEqs()] >> simp[LENGTH_DROP])) >>
  `LENGTH (DROP n (DROP 3 bs)) <= LENGTH (DROP 3 bs)` by simp[LENGTH_DROP] >>
  `LENGTH (DROP 3 bs) < LENGTH bs` by
     (Cases_on `bs` >> fs[] >> simp[LENGTH_DROP]) >>
  fs[]
End

(* Loop correctness: parsing the concatenation of encoded entries recovers
   them in order, given each entry's certData fits in 3 bytes and its
   extensions fit the 2-byte fields. *)
Theorem decodeCertEntries_loop_correct:
  !es acc.
    EVERY (\e. LENGTH e.certData < 16777216 /\
               EVERY (\x. LENGTH x.data < 65536) e.extensions /\
               LENGTH (FLAT (MAP encodeExtension e.extensions)) < 65536) es ==>
    decodeCertEntries_loop (FLAT (MAP encodeCertEntry es)) acc =
      SOME (REVERSE acc ++ es)
Proof
  Induct
  >- simp[Once decodeCertEntries_loop_def]
  >> rpt strip_tac
  >> fs[]
  >> simp[encodeCertEntry_def, len3_def]
  >> simp[Once decodeCertEntries_loop_def]
  >> `w2n (w24_of_len3 (n2w (LENGTH h.certData DIV 65536 MOD 256))
                       (n2w (LENGTH h.certData DIV 256 MOD 256))
                       (n2w (LENGTH h.certData MOD 256))) = LENGTH h.certData`
       by simp[len3_w24_roundtrip]
  >> asm_simp_tac bool_ss []
  >> PURE_REWRITE_TAC[GSYM APPEND_ASSOC]
  >> PURE_REWRITE_TAC[rich_listTheory.DROP_LENGTH_APPEND,
                      rich_listTheory.TAKE_LENGTH_APPEND]
  >> `decodeExtensionsR
        (encodeExtensions h.extensions ++ FLAT (MAP encodeCertEntry es)) =
        SOME (h.extensions, FLAT (MAP encodeCertEntry es))`
       by (irule decodeExtensionsR_correct >> fs[])
  >> asm_simp_tac bool_ss []
  >> simp[]
  >> simp[fetch "-" "certificateEntry_component_equality"]
QED

Definition encodeCertificate_def:
  encodeCertificate (c : certificate) : word8 list =
    encodeOpaque8 c.certificateRequestContext ++
    (let entries = encodeCertEntries c.certificateList in
       len3 (LENGTH entries) ++ entries)
End

Definition decodeCertificate_def:
  decodeCertificate (bs : word8 list) : certificate option =
    if LENGTH bs < 1 then NONE
    else
      let ctxLen = w2n (EL 0 bs) in
      let r1 = DROP 1 bs in
      if LENGTH r1 < ctxLen then NONE
      else
        let ctx = TAKE ctxLen r1 in
        let r2  = DROP ctxLen r1 in
        if LENGTH r2 < 3 then NONE
        else
          let total = w2n (w24_of_len3 (EL 0 r2) (EL 1 r2) (EL 2 r2)) in
          let r3    = DROP 3 r2 in
          if LENGTH r3 < total then NONE
          else
            case decodeCertEntries_loop (TAKE total r3) [] of
              | NONE => NONE
              | SOME entries =>
                  SOME <| certificateRequestContext := ctx;
                          certificateList := entries |>
End

Definition wfCertificate_def:
  wfCertificate (c : certificate) <=>
    LENGTH c.certificateRequestContext < 256 /\
    LENGTH (encodeCertEntries c.certificateList) < 16777216 /\
    EVERY (\e. LENGTH e.certData < 16777216 /\
               EVERY (\x. LENGTH x.data < 65536) e.extensions /\
               LENGTH (FLAT (MAP encodeExtension e.extensions)) < 65536)
          c.certificateList
End

Theorem decode_encode_certificate:
  !c. wfCertificate c ==>
      decodeCertificate (encodeCertificate c) = SOME c
Proof
  rw[wfCertificate_def] >>
  `encodeCertificate c =
     n2w (LENGTH c.certificateRequestContext) ::
     (c.certificateRequestContext ++
      (n2w ((LENGTH (encodeCertEntries c.certificateList) DIV 65536) MOD 256) ::
       n2w ((LENGTH (encodeCertEntries c.certificateList) DIV 256) MOD 256) ::
       n2w (LENGTH (encodeCertEntries c.certificateList) MOD 256) ::
       encodeCertEntries c.certificateList))`
    by simp[encodeCertificate_def, encodeOpaque8_def, len3_def] >>
  simp[decodeCertificate_def] >>
  `(n2w (LENGTH c.certificateRequestContext) : word8) =
     n2w (LENGTH c.certificateRequestContext)` by simp[] >>
  simp[w2n_n2w] >>
  `LENGTH c.certificateRequestContext MOD dimword (:8) =
     LENGTH c.certificateRequestContext`
    by (`dimword (:8) = 256` by EVAL_TAC >> simp[]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[GSYM rich_listTheory.APPEND_ASSOC] >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[len3_w24_roundtrip] >>
  simp[rich_listTheory.TAKE_LENGTH_APPEND] >>
  `decodeCertEntries_loop (encodeCertEntries c.certificateList) [] =
     SOME c.certificateList`
    by (simp[encodeCertEntries_def] >>
        qspecl_then [`c.certificateList`, `[]`] mp_tac
          decodeCertEntries_loop_correct >>
        impl_tac >- fs[] >> simp[]) >>
  simp[fetch "-" "certificate_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  ServerHello (§4.1.3)                                                      *)
(*                                                                            *)
(*  Wire: version(2) ++ random(32) ++ sidLen(1) ++ sid ++ cipherSuite(2) ++   *)
(*        compression(1) ++ encodeExtensions extensions                       *)
(* -------------------------------------------------------------------------- *)

Definition encodeServerHello_def:
  encodeServerHello (sh : serverHello) : word8 list =
    w16_to_bytes sh.legacyVersion ++
    sh.random ++
    (n2w (LENGTH sh.legacySessionId) :: sh.legacySessionId) ++
    w16_to_bytes sh.cipherSuite ++
    [sh.legacyCompression] ++
    encodeExtensions sh.extensions
End

Definition decodeServerHello_def:
  decodeServerHello (bs : word8 list) : serverHello option =
    if LENGTH bs < 2 then NONE
    else
      let legacyVersion = w16_of_bytes (EL 0 bs) (EL 1 bs) in
      let a1 = DROP 2 bs in
      if LENGTH a1 < 32 then NONE
      else
        let random = TAKE 32 a1 in
        let a2 = DROP 32 a1 in
        if LENGTH a2 < 1 then NONE
        else
          let sidLen = w2n (EL 0 a2) in
          let r1 = DROP 1 a2 in
          if LENGTH r1 < sidLen then NONE
          else
            let sid = TAKE sidLen r1 in
            let r2  = DROP sidLen r1 in
            if LENGTH r2 < 3 then NONE
            else
              let cipherSuite = w16_of_bytes (EL 0 r2) (EL 1 r2) in
              let comp = EL 2 r2 in
              let r3   = DROP 3 r2 in
              case decodeExtensions r3 of
                | NONE => NONE
                | SOME exts =>
                    SOME <| legacyVersion     := legacyVersion;
                            random            := random;
                            legacySessionId   := sid;
                            cipherSuite       := cipherSuite;
                            legacyCompression := comp;
                            extensions        := exts |>
End

Definition wfServerHello_def:
  wfServerHello (sh : serverHello) <=>
    LENGTH sh.random = 32 /\
    LENGTH sh.legacySessionId < 256 /\
    EVERY (\e. LENGTH e.data < 65536) sh.extensions /\
    LENGTH (FLAT (MAP encodeExtension sh.extensions)) < 65536
End

Theorem decode_encode_serverHello:
  !sh. wfServerHello sh ==>
       decodeServerHello (encodeServerHello sh) = SOME sh
Proof
  rw[wfServerHello_def] >>
  `encodeServerHello sh =
     w8_of_w16_hi sh.legacyVersion :: w8_of_w16_lo sh.legacyVersion ::
     (sh.random ++
      (n2w (LENGTH sh.legacySessionId) ::
       (sh.legacySessionId ++
        (w8_of_w16_hi sh.cipherSuite :: w8_of_w16_lo sh.cipherSuite ::
         sh.legacyCompression ::
         encodeExtensions sh.extensions))))`
    by simp[encodeServerHello_def, w16_to_bytes_def] >>
  simp[decodeServerHello_def] >>
  simp[w16_of_to_bytes] >>
  qpat_x_assum `LENGTH sh.random = 32`
    (fn th => PURE_REWRITE_TAC[GSYM th]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  `LENGTH sh.legacySessionId MOD dimword (:8) = LENGTH sh.legacySessionId`
    by (`dimword (:8) = 256` by EVAL_TAC >> simp[]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[w16_of_to_bytes] >>
  simp[decode_encode_extensions] >>
  simp[fetch "-" "serverHello_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  ClientHello (§4.1.2)                                                      *)
(*                                                                            *)
(*  Wire: version(2) ++ random(32) ++ sidLen(1) ++ sid ++                     *)
(*        cipherSuitesLen(2) ++ FLAT(map w16 cipherSuites) ++                 *)
(*        compLen(1) ++ legacyCompression ++ encodeExtensions extensions      *)
(* -------------------------------------------------------------------------- *)

Definition encodeClientHello_def:
  encodeClientHello (ch : clientHello) : word8 list =
    w16_to_bytes ch.legacyVersion ++
    ch.random ++
    (n2w (LENGTH ch.legacySessionId) :: ch.legacySessionId) ++
    encodeW16List ch.cipherSuites ++
    (n2w (LENGTH ch.legacyCompression) :: ch.legacyCompression) ++
    encodeExtensions ch.extensions
End

Definition decodeClientHello_def:
  decodeClientHello (bs : word8 list) : clientHello option =
    if LENGTH bs < 2 then NONE
    else
      let legacyVersion = w16_of_bytes (EL 0 bs) (EL 1 bs) in
      let a1 = DROP 2 bs in
      if LENGTH a1 < 32 then NONE
      else
        let random = TAKE 32 a1 in
        let a2 = DROP 32 a1 in
        if LENGTH a2 < 1 then NONE
        else
          let sidLen = w2n (EL 0 a2) in
          let a3 = DROP 1 a2 in
          if LENGTH a3 < sidLen then NONE
          else
            let sid = TAKE sidLen a3 in
            let a4  = DROP sidLen a3 in
            if LENGTH a4 < 2 then NONE
            else
              let csTotal = w2n (w16_of_bytes (EL 0 a4) (EL 1 a4)) in
              let a5 = DROP 2 a4 in
              if LENGTH a5 < csTotal then NONE
              else
                (case decodeW16s_loop (csTotal DIV 2) (TAKE csTotal a5) of
                   | NONE => NONE
                   | SOME (suites, _) =>
                       let a6 = DROP csTotal a5 in
                       if LENGTH a6 < 1 then NONE
                       else
                         let compLen = w2n (EL 0 a6) in
                         let a7 = DROP 1 a6 in
                         if LENGTH a7 < compLen then NONE
                         else
                           let comp = TAKE compLen a7 in
                           let a8   = DROP compLen a7 in
                           (case decodeExtensions a8 of
                              | NONE => NONE
                              | SOME exts =>
                                  SOME <| legacyVersion     := legacyVersion;
                                          random            := random;
                                          legacySessionId   := sid;
                                          cipherSuites      := suites;
                                          legacyCompression := comp;
                                          extensions        := exts |>))
End

Definition wfClientHello_def:
  wfClientHello (ch : clientHello) <=>
    LENGTH ch.random = 32 /\
    LENGTH ch.legacySessionId < 256 /\
    LENGTH ch.cipherSuites < 32768 /\
    LENGTH ch.legacyCompression < 256 /\
    EVERY (\e. LENGTH e.data < 65536) ch.extensions /\
    LENGTH (FLAT (MAP encodeExtension ch.extensions)) < 65536
End

Theorem decode_encode_clientHello:
  !ch. wfClientHello ch ==>
       decodeClientHello (encodeClientHello ch) = SOME ch
Proof
  rw[wfClientHello_def] >>
  `encodeClientHello ch =
     w8_of_w16_hi ch.legacyVersion :: w8_of_w16_lo ch.legacyVersion ::
     (ch.random ++
      (n2w (LENGTH ch.legacySessionId) ::
       (ch.legacySessionId ++
        (w8_of_w16_hi (n2w (LENGTH (encodeW16ListBody ch.cipherSuites))) ::
         w8_of_w16_lo (n2w (LENGTH (encodeW16ListBody ch.cipherSuites))) ::
         (encodeW16ListBody ch.cipherSuites ++
          (n2w (LENGTH ch.legacyCompression) ::
           (ch.legacyCompression ++
            encodeExtensions ch.extensions)))))))`
    by simp[encodeClientHello_def, w16_to_bytes_def, encodeW16List_def] >>
  simp[decodeClientHello_def] >>
  simp[w16_of_to_bytes] >>
  qpat_x_assum `LENGTH ch.random = 32`
    (fn th => PURE_REWRITE_TAC[GSYM th]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  `LENGTH ch.legacySessionId MOD dimword (:8) = LENGTH ch.legacySessionId`
    by (`dimword (:8) = 256` by EVAL_TAC >> simp[]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  `LENGTH (encodeW16ListBody ch.cipherSuites) = 2 * LENGTH ch.cipherSuites`
    by simp[encodeW16ListBody_length] >>
  `(2 * LENGTH ch.cipherSuites) < 65536` by simp[] >>
  `w2n (w16_of_bytes
          (w8_of_w16_hi (n2w (LENGTH (encodeW16ListBody ch.cipherSuites))))
          (w8_of_w16_lo (n2w (LENGTH (encodeW16ListBody ch.cipherSuites))))) =
     LENGTH (encodeW16ListBody ch.cipherSuites)`
    by (simp[] >> simp[w16_len_roundtrip]) >>
  simp[] >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  `(2 * LENGTH ch.cipherSuites) DIV 2 = LENGTH ch.cipherSuites` by simp[] >>
  simp[] >>
  `decodeW16s_loop (LENGTH ch.cipherSuites)
       (encodeW16ListBody ch.cipherSuites) =
     SOME (ch.cipherSuites, [])`
    by (simp[encodeW16ListBody_def] >>
        qspecl_then [`ch.cipherSuites`, `[]`] mp_tac decodeW16s_loop_correct >>
        simp[]) >>
  simp[] >>
  qpat_x_assum `LENGTH (encodeW16ListBody ch.cipherSuites) = 2 * LENGTH ch.cipherSuites`
    (fn th => PURE_REWRITE_TAC[GSYM th]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  `LENGTH ch.legacyCompression MOD dimword (:8) = LENGTH ch.legacyCompression`
    by (`dimword (:8) = 256` by EVAL_TAC >> simp[]) >>
  simp[rich_listTheory.DROP_LENGTH_APPEND, rich_listTheory.TAKE_LENGTH_APPEND] >>
  simp[decode_encode_extensions] >>
  simp[fetch "-" "clientHello_component_equality"]
QED

val _ = export_theory ();
