(* tls_wireScript.sml

   HOL4 formal model of the TLS 1.3 wire formats (RFC 8446), Track B1,
   sub-worker 1. This theory is derived from the RFC (and aligned with
   the Phase 0 SML signatures TLS_RECORD / TLS_HANDSHAKE / TLS_EXTENSIONS
   in tls.sig), so it proceeds in parallel with all functional work.

   Conventions mirror the SML library:
     - bytes are HOL4 ``:word8`` values; byte strings are ``:word8 list``;
     - multi-byte integers are big-endian;
     - every decoder is total: a malformed input yields ``NONE``, never a
       partial value;
     - datatypes are exhaustive over the RFC's named values and carry an
       ``Other`` constructor only where the SML does (alert descriptions).

   Round-trip theorems of the form

       decode (encode x) = SOME (x, [])

   are stated (and proved by EVAL for the small cases) for each structure.
*)

open HolKernel Parse boolLib bossLib;
open listTheory optionTheory wordsTheory;

val _ = new_theory "tls_wire";

(* -------------------------------------------------------------------------- *)
(*  Trusted (but mechanical) byte/word helpers                                *)
(* -------------------------------------------------------------------------- *)

(* These are provable from fcpTheory / wordTheory by EVAL; the exact shape
   depends on HOL4's word library which is still building at write time.
   Stated as axioms here so the rest of the theory type-checks; Phase 7
   replaces each with a real Definition + EVAL proof. *)

(* High/low byte extraction for the 16-bit big-endian encoder. *)
Definition w8_of_w16_hi_def:
  w8_of_w16_hi (w : word16) : word8 = w2w (w >>> 8)
End

Definition w8_of_w16_lo_def:
  w8_of_w16_lo (w : word16) : word8 = w2w w
End

(* w16_of_bytes hi lo = (hi << 8) | lo, big-endian reassembly. *)
Definition w16_of_bytes_def:
  w16_of_bytes (hi : word8) (lo : word8) : word16 =
    (w2w hi << 8) || w2w lo
End

(* w24_of_len3 hi mid lo reassembles a 24-bit length. *)
Definition w24_of_len3_def:
  w24_of_len3 (hi : word8) (mid : word8) (lo : word8) : word32 =
    (w2w hi << 16) || (w2w mid << 8) || w2w lo
End

(* len3 n splits a 24-bit length into three bytes, high byte first. *)
Definition len3_def:
  len3 (n : num) : word8 list =
    [n2w ((n DIV 65536) MOD 256);
     n2w ((n DIV 256) MOD 256);
     n2w (n MOD 256)]
End

(* mk_tlsPlaintext / mk_tlsCiphertext / mk_handshakeMessage are the
   record constructors generated by Datatype; the calls below rely on
   them, so the Datatype declarations must precede their use. *)

(* -------------------------------------------------------------------------- *)
(*  Shared byte / word primitives                                             *)
(* -------------------------------------------------------------------------- *)

(* The TLS legacy record version field: always 0x0303 on the wire even for
   TLS 1.3 (RFC 8446 5.1). Kept as a 16-bit word constant. *)
Definition legacyVersion_def:
  legacyVersion : word16 = 0x0303w
End

(* Encode a 16-bit big-endian integer as a 2-byte list. The high byte is
   the top 8 bits; the low byte is the bottom 8. Defined in terms of the
   w8_of_w16_hi/lo helpers axiomatised at the bottom of this file. *)
Definition w16_to_bytes_def:
  w16_to_bytes (w : word16) : word8 list =
    [w8_of_w16_hi w; w8_of_w16_lo w]
End

(* -------------------------------------------------------------------------- *)
(*  Word reconstruction lemmas (proved by bit-blasting / w2n arithmetic)      *)
(* -------------------------------------------------------------------------- *)

(* A 16-bit word survives the split-into-bytes / reassemble round-trip. *)
Theorem w16_of_to_bytes:
  !w:word16. w16_of_bytes (w8_of_w16_hi w) (w8_of_w16_lo w) = w
Proof
  rw[w16_of_bytes_def, w8_of_w16_hi_def, w8_of_w16_lo_def] >>
  blastLib.BBLAST_TAC
QED

(* Encoding a length < 2^16 as two bytes and reading it back yields the
   length unchanged. *)
Theorem w16_len_roundtrip:
  !len. len < 65536 ==>
        w2n (w16_of_bytes (w8_of_w16_hi (n2w len)) (w8_of_w16_lo (n2w len))) = len
Proof
  rw[w16_of_to_bytes] >>
  simp[w2n_n2w] >>
  `dimword (:16) = 65536` by EVAL_TAC >>
  simp[]
QED

(* A 24-bit value held in a word32 survives split/reassemble.  The bound
   gives the bit-blaster the information that the top byte is zero. *)
Theorem w24_recon:
  !w:word32. w <+ 0x1000000w ==>
     w24_of_len3 (w2w (w >>> 16)) (w2w (w >>> 8)) (w2w w) = w
Proof
  rw[w24_of_len3_def] >> rpt strip_tac >> blastLib.FULL_BBLAST_TAC
QED

(* n2w absorbs a redundant MOD 256 at type word8 (dimword(:8) = 256). *)
Theorem n2w_mod256:
  !a. (n2w (a MOD 256) : word8) = n2w a
Proof
  strip_tac >> `256 = dimword (:8)` by EVAL_TAC >> pop_assum SUBST1_TAC >>
  simp[n2w_mod]
QED

(* Encoding a length < 2^24 as three big-endian bytes and reading it back
   yields the length unchanged. *)
Theorem len3_w24_roundtrip:
  !len. len < 16777216 ==>
    w2n (w24_of_len3 (n2w ((len DIV 65536) MOD 256))
                     (n2w ((len DIV 256) MOD 256))
                     (n2w (len MOD 256))) = len
Proof
  rpt strip_tac >>
  `dimword (:32) = 4294967296` by EVAL_TAC >>
  `(2:num) ** 16 = 65536` by EVAL_TAC >>
  `(2:num) ** 8 = 256` by EVAL_TAC >>
  `len MOD dimword (:32) = len` by simp[arithmeticTheory.LESS_MOD] >>
  `dimword (:8) = 256` by EVAL_TAC >>
  `w24_of_len3 (n2w ((len DIV 65536) MOD 256))
               (n2w ((len DIV 256) MOD 256))
               (n2w (len MOD 256)) = (n2w len : word32)` by (
     `(n2w ((len DIV 65536) MOD 256) : word8) = w2w ((n2w len : word32) >>> 16)` by
        simp[w2w_def, w2n_lsr, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     `(n2w ((len DIV 256) MOD 256) : word8) = w2w ((n2w len : word32) >>> 8)` by
        simp[w2w_def, w2n_lsr, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     `(n2w (len MOD 256) : word8) = w2w (n2w len : word32)` by
        simp[w2w_def, w2n_n2w, arithmeticTheory.MOD_MOD] >>
     ASM_REWRITE_TAC[] >> irule w24_recon >>
     simp[WORD_LO, w2n_n2w]) >>
  simp[w2n_n2w]
QED

(* -------------------------------------------------------------------------- *)
(*  Content type (RFC 8446 5.1 / 5.2)                                         *)
(* -------------------------------------------------------------------------- *)

Datatype:
  contentType =
      Invalid
    | ChangeCipherSpec
    | Alert
    | Handshake
    | ApplicationData
End

Definition encodeContentType_def:
  (encodeContentType Invalid          = 0x00w : word8) /\
  (encodeContentType ChangeCipherSpec = 0x14w) /\
  (encodeContentType Alert            = 0x15w) /\
  (encodeContentType Handshake        = 0x16w) /\
  (encodeContentType ApplicationData  = 0x17w)
End

Definition decodeContentType_def:
  (decodeContentType (b : word8) =
     if b = 0x00w then SOME Invalid else
     if b = 0x14w then SOME ChangeCipherSpec else
     if b = 0x15w then SOME Alert else
     if b = 0x16w then SOME Handshake else
     if b = 0x17w then SOME ApplicationData else
     NONE)
End

Theorem decode_encode_contentType:
  !ct. decodeContentType (encodeContentType ct) = SOME ct
Proof
  Cases >> EVAL_TAC
QED

(* -------------------------------------------------------------------------- *)
(*  Record headers (RFC 8446 5.1)                                             *)
(* -------------------------------------------------------------------------- *)

Datatype:
  tlsPlaintext =
    <| contentType : contentType;
       (* legacy_record_version is always legacyVersion, so it is omitted
          from the model and re-introduced on encode. *)
       fragment     : word8 list |>
End

Datatype:
  tlsCiphertext =
    <| contentType       : contentType;
       encryptedRecord   : word8 list |>
End

(* 5-byte header: [type:1][version:2][length:2], then the fragment.
   Length is the fragment length; we assume < 2^14 (enforced elsewhere). *)
Definition encodePlaintext_def:
  encodePlaintext (r : tlsPlaintext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.fragment) : word16) ++
     r.fragment)
End

Definition decodePlaintext_def:
  decodePlaintext (bs : word8 list) : (tlsPlaintext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; fragment := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

(* Round-trip: decoding an encoded record returns the record and no
   remainder. Provable by EVAL on concrete records; the general case
   reduces to list arithmetic. *)
(* The 16-bit length field caps a fragment at 2^16-1 bytes (TLS itself caps
   records well below this, at 2^14); under that bound the round-trip holds. *)
Theorem decode_encode_plaintext:
  !r. LENGTH r.fragment < 65536 ==>
      decodePlaintext (encodePlaintext r) = SOME (r, [])
Proof
  strip_tac >> strip_tac >>
  `encodePlaintext r =
     encodeContentType r.contentType ::
     w8_of_w16_hi legacyVersion :: w8_of_w16_lo legacyVersion ::
     w8_of_w16_hi (n2w (LENGTH r.fragment)) ::
     w8_of_w16_lo (n2w (LENGTH r.fragment)) :: r.fragment`
    by simp[encodePlaintext_def, w16_to_bytes_def] >>
  simp[decodePlaintext_def, decode_encode_contentType, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "tlsPlaintext_component_equality"]
QED

(* Ciphertext framing is identical in shape (outer type is always
   ApplicationData under a traffic key, but the wire format is the same). *)
Definition encodeCiphertext_def:
  encodeCiphertext (r : tlsCiphertext) : word8 list =
    encodeContentType r.contentType ::
    (w16_to_bytes legacyVersion ++
     w16_to_bytes (n2w (LENGTH r.encryptedRecord) : word16) ++
     r.encryptedRecord)
End

Definition decodeCiphertext_def:
  decodeCiphertext (bs : word8 list) : (tlsCiphertext # word8 list) option =
    if LENGTH bs < 5 then NONE
    else
      let ctB   = EL 0 bs in
      let n     = w2n (w16_of_bytes (EL 3 bs) (EL 4 bs)) in
      case decodeContentType ctB of
        | NONE => NONE
        | SOME ct =>
            if LENGTH bs < 5 + n then NONE
            else SOME (<| contentType := ct; encryptedRecord := TAKE n (DROP 5 bs) |>,
                       DROP (5 + n) bs)
End

Theorem decode_encode_ciphertext:
  !r. LENGTH r.encryptedRecord < 65536 ==>
      decodeCiphertext (encodeCiphertext r) = SOME (r, [])
Proof
  strip_tac >> strip_tac >>
  `encodeCiphertext r =
     encodeContentType r.contentType ::
     w8_of_w16_hi legacyVersion :: w8_of_w16_lo legacyVersion ::
     w8_of_w16_hi (n2w (LENGTH r.encryptedRecord)) ::
     w8_of_w16_lo (n2w (LENGTH r.encryptedRecord)) :: r.encryptedRecord`
    by simp[encodeCiphertext_def, w16_to_bytes_def] >>
  simp[decodeCiphertext_def, decode_encode_contentType, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "tlsCiphertext_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message types (RFC 8446 4)                                      *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeType =
      ClientHello
    | ServerHello
    | NewSessionTicket
    | EndOfEarlyData
    | EncryptedExtensions
    | Certificate
    | CertificateRequest
    | CertificateVerify
    | Finished
    | KeyUpdate
    | MessageHash
End

Definition encodeHandshakeType_def:
  (encodeHandshakeType ClientHello         = 0x01w : word8) /\
  (encodeHandshakeType ServerHello         = 0x02w) /\
  (encodeHandshakeType NewSessionTicket    = 0x04w) /\
  (encodeHandshakeType EndOfEarlyData      = 0x05w) /\
  (encodeHandshakeType EncryptedExtensions = 0x08w) /\
  (encodeHandshakeType Certificate         = 0x0Bw) /\
  (encodeHandshakeType CertificateRequest  = 0x0Dw) /\
  (encodeHandshakeType CertificateVerify   = 0x0Fw) /\
  (encodeHandshakeType Finished            = 0x14w) /\
  (encodeHandshakeType KeyUpdate          = 0x18w) /\
  (encodeHandshakeType MessageHash        = 0xFEw)
End

Definition decodeHandshakeType_def:
  (decodeHandshakeType (b : word8) =
     if b = 0x01w then SOME ClientHello else
     if b = 0x02w then SOME ServerHello else
     if b = 0x04w then SOME NewSessionTicket else
     if b = 0x05w then SOME EndOfEarlyData else
     if b = 0x08w then SOME EncryptedExtensions else
     if b = 0x0Bw then SOME Certificate else
     if b = 0x0Dw then SOME CertificateRequest else
     if b = 0x0Fw then SOME CertificateVerify else
     if b = 0x14w then SOME Finished else
     if b = 0x18w then SOME KeyUpdate else
     if b = 0xFEw then SOME MessageHash else
     NONE)
End

Theorem decode_encode_handshakeType:
  !t. decodeHandshakeType (encodeHandshakeType t) = SOME t
Proof
  Cases >> EVAL_TAC
QED

(* -------------------------------------------------------------------------- *)
(*  Handshake message framing (RFC 8446 4)                                    *)
(* -------------------------------------------------------------------------- *)

Datatype:
  handshakeMessage =
    <| msgType : handshakeType;
       body    : word8 list |>
End

(* A handshake message on the wire is [type:1][length:3][body]. The length
   is a 24-bit big-endian integer; we model it as three word8 bytes. *)
Definition encodeMessage_def:
  encodeMessage (m : handshakeMessage) : word8 list =
    encodeHandshakeType m.msgType ::
    (len3 (LENGTH m.body) ++ m.body)
End

Definition decodeMessage_def:
  decodeMessage (bs : word8 list) : (handshakeMessage # word8 list) option =
    if LENGTH bs < 4 then NONE
    else
      let t = EL 0 bs in
      let n = w2n (w24_of_len3 (EL 1 bs) (EL 2 bs) (EL 3 bs)) in
      case decodeHandshakeType t of
        | NONE => NONE
        | SOME ht =>
            if LENGTH bs < 4 + n then NONE
            else SOME (<| msgType := ht; body := TAKE n (DROP 4 bs) |>,
                       DROP (4 + n) bs)
End

(* The 24-bit length field caps a handshake body at 2^24-1 bytes (the RFC
   8446 limit); under that bound the round-trip holds. *)
Theorem decode_encode_message:
  !m. LENGTH m.body < 16777216 ==>
      decodeMessage (encodeMessage m) = SOME (m, [])
Proof
  strip_tac >> strip_tac >>
  `encodeMessage m =
     encodeHandshakeType m.msgType ::
     n2w ((LENGTH m.body DIV 65536) MOD 256) ::
     n2w ((LENGTH m.body DIV 256) MOD 256) ::
     n2w (LENGTH m.body MOD 256) :: m.body`
    by simp[encodeMessage_def, len3_def] >>
  simp[decodeMessage_def, decode_encode_handshakeType, len3_w24_roundtrip] >>
  simp[TAKE_LENGTH_ID, DROP_LENGTH_NIL, fetch "-" "handshakeMessage_component_equality"]
QED

(* -------------------------------------------------------------------------- *)
(*  Extensions (RFC 8446 4.2)                                                *)
(* -------------------------------------------------------------------------- *)

Datatype:
  extension = <| extType : word16; data : word8 list |>
End

(* Extension block = 2-byte total length, then a sequence of entries,
   each [type:2][length:2][data]. *)
Definition encodeExtension_def:
  encodeExtension (e : extension) : word8 list =
    w16_to_bytes e.extType ++
    w16_to_bytes (n2w (LENGTH e.data) : word16) ++
    e.data
End

Definition encodeExtensions_def:
  encodeExtensions (es : extension list) : word8 list =
    let body = FLAT (MAP encodeExtension es) in
    w16_to_bytes (n2w (LENGTH body) : word16) ++ body
End

(* Tail-recursive parser over the extension body. Each iteration reads a
   4-byte entry header; a truncated length, a length exceeding the
   remaining budget, or trailing junk after `total` bytes yields NONE. *)
Definition decodeExts_loop_def:
  (decodeExts_loop [] acc = SOME (REVERSE acc)) /\
  (decodeExts_loop (h0::h1::l0::l1::rest) acc =
     let extType = w16_of_bytes h0 h1 in
     let n       = w2n (w16_of_bytes l0 l1) in
     if LENGTH rest < n then NONE
     else decodeExts_loop (DROP n rest)
                          (<| extType := extType; data := TAKE n rest |> :: acc)) /\
  (decodeExts_loop [_] acc = NONE) /\
  (decodeExts_loop [_;_] acc = NONE) /\
  (decodeExts_loop [_;_;_] acc = NONE)
Termination
  WF_REL_TAC `measure (LENGTH o FST)` \\ rw [] \\ DECIDE_TAC
End

Definition decodeExtensions_def:
  decodeExtensions (bs : word8 list) : extension list option =
    if LENGTH bs < 2 then NONE
    else
      let total = w2n (w16_of_bytes (EL 0 bs) (EL 1 bs)) in
      if LENGTH bs < 2 + total then NONE
      else decodeExts_loop (TAKE total (DROP 2 bs)) []
End

(* The loop is correct: parsing the concatenation of encoded extensions
   recovers them in order (modulo the reverse-accumulator), provided each
   extension's data fits in the 2-byte length field. *)
Theorem decodeExts_loop_correct:
  !es acc.
    EVERY (\e. LENGTH e.data < 65536) es ==>
    decodeExts_loop (FLAT (MAP encodeExtension es)) acc = SOME (REVERSE acc ++ es)
Proof
  Induct
  >- simp[decodeExts_loop_def]
  >> rpt strip_tac
  >> fs[]
  >> simp[encodeExtension_def, w16_to_bytes_def]
  >> simp[decodeExts_loop_def, w16_of_to_bytes, w16_len_roundtrip,
          rich_listTheory.TAKE_LENGTH_APPEND, rich_listTheory.DROP_LENGTH_APPEND]
  >> simp[fetch "-" "extension_component_equality"]
QED

(* Full extension-block round-trip.  Two honest bounds: each extension's
   data is < 2^16 bytes, and the concatenated block is < 2^16 bytes (both
   enforced by the 2-byte length fields on the wire). *)
Theorem decode_encode_extensions:
  !es. EVERY (\e. LENGTH e.data < 65536) es /\
       LENGTH (FLAT (MAP encodeExtension es)) < 65536 ==>
       decodeExtensions (encodeExtensions es) = SOME es
Proof
  rpt strip_tac >>
  simp[decodeExtensions_def, encodeExtensions_def, w16_to_bytes_def] >>
  simp[w16_of_to_bytes, w16_len_roundtrip, rich_listTheory.TAKE_LENGTH_APPEND,
       rich_listTheory.DROP_LENGTH_APPEND] >>
  simp[decodeExts_loop_correct]
QED

(* -------------------------------------------------------------------------- *)
(*  Concrete handshake message bodies (simplified)                            *)
(* -------------------------------------------------------------------------- *)

Datatype:
  clientHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuites       : word16 list;
       legacyCompression  : word8 list;
       extensions         : extension list |>
End

Datatype:
  serverHello =
    <| legacyVersion       : word16;
       random             : word8 list;     (* 32 bytes              *)
       legacySessionId    : word8 list;
       cipherSuite        : word16;
       legacyCompression  : word8;
       extensions         : extension list |>
End

Datatype:
  certificateEntry =
    <| certData   : word8 list;
       extensions : extension list |>
End

Datatype:
  certificate =
    <| certificateRequestContext : word8 list;
       certificateList           : certificateEntry list |>
End

Datatype:
  certificateVerify =
    <| sigAlg   : word16;
       sigBytes : word8 list |>
End

Datatype:
  finished = <| verifyData : word8 list |>
End

Datatype:
  newSessionTicket =
    <| ticketLifetime : word32;
       ticketAgeAdd   : word32;
       ticketNonce    : word8 list;
       ticket         : word8 list;
       extensions     : extension list |>
End

(* --- Finished (RFC 8446 4.4.4) -----------------------------------------

   The Finished body is exactly verify_data (no internal framing); its
   length is fixed by the hash and is always non-empty.  This mirrors the
   SML `encodeFinished`/`decodeFinished` in tls.sml, which return NONE on an
   empty input. *)

Definition encodeFinished_def:
  encodeFinished (f : finished) : word8 list = f.verifyData
End
Definition decodeFinished_def:
  decodeFinished (bs : word8 list) : finished option =
    if bs = [] then NONE else SOME <| verifyData := bs |>
End

Theorem finished_roundtrip:
  !f. f.verifyData <> [] ==> decodeFinished (encodeFinished f) = SOME f
Proof
  rw[encodeFinished_def, decodeFinished_def] >>
  simp[fetch "-" "finished_component_equality"]
QED

(* --- CertificateVerify (RFC 8446 4.4.3) --------------------------------

   Wire form: [sigAlg:2][sigLen:2][signature].  Mirrors the SML
   `encodeCertificateVerify`/`decodeCertificateVerify`. *)

Definition encodeCertificateVerify_def:
  encodeCertificateVerify (cv : certificateVerify) : word8 list =
    w16_to_bytes cv.sigAlg ++
    w16_to_bytes (n2w (LENGTH cv.sigBytes) : word16) ++
    cv.sigBytes
End
Definition decodeCertificateVerify_def:
  decodeCertificateVerify (bs : word8 list) : certificateVerify option =
    if LENGTH bs < 4 then NONE
    else
      let sigAlg = w16_of_bytes (EL 0 bs) (EL 1 bs) in
      let n      = w2n (w16_of_bytes (EL 2 bs) (EL 3 bs)) in
      if LENGTH bs < 4 + n then NONE
      else SOME <| sigAlg := sigAlg; sigBytes := TAKE n (DROP 4 bs) |>
End

Theorem certificateVerify_roundtrip:
  !cv. LENGTH cv.sigBytes < 65536 ==>
       decodeCertificateVerify (encodeCertificateVerify cv) = SOME cv
Proof
  strip_tac >> strip_tac >>
  `encodeCertificateVerify cv =
     w8_of_w16_hi cv.sigAlg :: w8_of_w16_lo cv.sigAlg ::
     w8_of_w16_hi (n2w (LENGTH cv.sigBytes)) ::
     w8_of_w16_lo (n2w (LENGTH cv.sigBytes)) :: cv.sigBytes`
    by simp[encodeCertificateVerify_def, w16_to_bytes_def] >>
  simp[decodeCertificateVerify_def, w16_of_to_bytes, w16_len_roundtrip] >>
  simp[TAKE_LENGTH_ID, fetch "-" "certificateVerify_component_equality"]
QED

(* --- ClientHello / ServerHello / Certificate / NewSessionTicket --------

   These structures carry nested, length-prefixed vectors and *lists* of
   sub-structures (cipher-suite lists, an extension block whose presence is
   optional, and -- for Certificate -- a list of CertificateEntry each with
   its own 3-byte length prefix and extension block).  Their SML encoders /
   decoders in tls.sml are NOT clean inverses in all cases (e.g. an absent
   trailing extension block decodes to []), so an unconditional round-trip
   theorem does not hold without additional well-formedness side conditions.

   To keep this theory SOUND we do NOT state placeholder `cheat` round-trip
   theorems for them (a `cheat` on a non-theorem would make tls_wireTheory
   inconsistent).  The datatypes above record the intended model; the
   mechanized codecs and their conditional round-trip proofs are tracked as
   open work in proof/PROOF_STATUS.md.  The reusable framing layer needed to
   discharge them (the record/handshake/extension round-trips above) is
   fully proved. *)

val _ = export_theory ();
